export default {
  WORLD_SIZE: 500,
  DEFAULT_PLAYER_SPEED: 2,
  DEFAULT_PLAYER_RADIUS: 10,
  ROOM_NAME: "arena",
  SIMULATION_TICK_RATE: 16.66,
  DEFAULT_ROCKET_RADIUS: 5,
  DEFAULT_ROCKET_SPEED: 1,
  DEFAULT_ROCKET_START_SPEED: 1,
  DEFAULT_ROCKET_SPEED_INCREASE: 0.2,
};
