export default {
  WORLD_SIZE: 800,
  PLAYER_SPEED: 2,
  PLAYER_RADIUS: 10,
  ROOM_NAME: "arena",
  SIMULATION_TICK_RATE: 16.66,
  ROCKET_RADIUS: 5,
  ROCKET_SPEED: 1,
  ROCKET_START_SPEED: 1,
  ROCKET_SPEED_INCREASE: 0.2,
  BOT_ENABLED: true,
  BOT_COUNT: 3,
};
