export enum PHASE_NAME {
  ARENA_WAITING = "ARENA_WAITING",
  ARENA_COUNTDOWN = "ARENA_COUNTDOWN",
  ARENA_PLAYING = "ARENA_PLAYING",
  ARENA_FINISH = "ARENA_FINISH",
}

export enum ACTOR_TYPE {
  PLAYER = "PLAYER",
  BOT = "BOT",
}